version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - mvn clean compile test
  build:
    commands:
      - mvn package
reports:
  SurefireReports: #test file information
    files:
      - '**/*'
    base-directory: 'target/surefire-reports'
    discard-paths: false #do not remove file paths from test result files
artifacts:
  files:
    - 'appspec.yml'
    - 'template.yml'
    - 'prod_template.yml'
    - 'scripts/*'
    - 'target/ROOT.war'
    - Dockerfile
    - buildspec_docker.yml
  discard-paths: no
