version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - mvn clean compile test
  build:
    commands:
      - mvn package
reports:
      arn:aws:codebuild:us-east-1:926976112852:report-group/demo: #test file information
      files:
        - 'TEST-com.aws.codestar.projecttemplates.controller.HelloWorldControllerTest.xml'
      base-directory: 'target/surefire-reports'
      discard-paths: false #do not remove file paths from test result files
artifacts:
  files:
    - 'appspec.yml'
    - 'template.yml'
    - 'prod_template.yml'
    - 'scripts/*'
    - 'target/ROOT.war'
    - Dockerfile
    - buildspec_docker.yml
  discard-paths: no
