version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - mvn clean compile test
  build:
    commands:
      - mvn package
artifacts:
  files:
    - 'appspec.yml'
    - 'template.yml'
    - 'prod_template.yml'
    - 'scripts/*'
    - 'target/ROOT.war'
    - Dockerfile
    - buildspec_docker.yml
  discard-paths: no
